% find_skel_intersection
%
% 431-400 Year Long Project, LA1 - Medical Image Processing 2003
% Supervisor     :  Dr Lachlan Andrew
% Group Members  :  Alister Fong    78629   a.fong1@ugrad.unimelb.edu.au
%                   Lee Siew Teng   102519  s.lee1@ugrad.unimelb.edu.au
%                   Loh Jien Mei    103650  j.loh1@ugrad.unimelb.edu.au
%
% Related programs : find_skel_ends.m
%
% test_find_skel_intersection.m (RUN THIS!!)
%       Tests the function "find_find_skel_intersection"
% find_skel_intersection.m (USE THIS!!)
%       Determines the locations of intersecting points in the given skeleton.
%	The binary image should have already been processed by the function
%	'bwmorph' and the 'thin' option, in the image processing library. 
%	For further examples look at the testfile 'test_find_skel_intersection'.
% sortclasses (USE THIS!!)
%       To sort the coordinates which are in a continuous group into different classes
% euclidean_distance.m (USE THIS!!)
%         Calculates the euclidean_distance between 2 points